"""Stage 10 - phylogenomics.

Responsibilities:

* summarise the core-gene and core-SNP alignments;
* parse the newick tree and extract tip labels;
* **validate that the tree tip set matches the master sample manifest
  exactly** - no extra tips, no missing tips, no duplicates;
* **produce `lineage_label`**, which is what the lineage-aware stages consume.

That last item exists because nothing produced it. `build_tree_outputs` wrote
`sample_id` / `tree_tip_label` / `source` and passed the two-column
`REQUIRED_TREE_METADATA` to `write_tsv`, so the contract's five columns
(`docs/data_contract.md`) and the written columns disagreed, `extrasaction`
dropped the extras silently - `lineage_label`, `st` *and* `source` - and
`load_tree_metadata` then read every sample as the literal string `"unknown"`.
A reader who installed panaroo and fixed gubbins arrived at that wall with every
explanation the refusal message offered already exhausted.

Ruling R4: **`lineage_label` IS the MLST sequence type from stage 3**, read from
that stage's own on-disk table at its contracted path, and the method is
recorded so a result always says how its lineages were defined. Cutting the
tree into clades is deferred and is not implemented here; `lineage.method`
accepts one value, and `LineageConfig` refuses anything else at load time.

The alignment check above is the reason this module exists. A phylogenetic tree
whose tips do not correspond one-to-one with the samples in the manifest will
silently corrupt every lineage-aware analysis downstream (stages 13, 14 and
the annotated tree figure), so a mismatch is a hard failure with a precise
diff rather than a warning.

Alignment and tree building themselves are delegated to Panaroo, SNP-sites
and IQ-TREE 2, which are invoked by the adapter layer when installed.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, FrozenSet, List, Optional, Sequence, Set, Tuple

from ..config.loader import PipelineConfig
from ..errors import DataContractError, PipelineError, TreeSampleMismatchError
from ..io.fasta import summarise_alignment
from ..io.tsv import read_tsv, write_tsv
from ..logging_utils import get_logger
from ..manifest import SampleManifest
from ..models import RunMode

LOGGER = get_logger("stages.phylogeny")

TREE_METADATA_COLUMNS: Tuple[str, ...] = (
    "sample_id",
    "tree_tip_label",
    "lineage_label",
    "st",
    "source",
)

REQUIRED_TREE_METADATA = ("sample_id", "tree_tip_label")

#: Stage 3's contracted output path, relative to `config.tool_output_root(mode)`.
#: Named here as well as in `docs/data_contract.md` because the refusal below
#: has to print the path a reader can go and look at, and a path assembled from
#: two places that each think they own it is a path that will be wrong once.
MLST_RESULTS_RELATIVE = ("mlst", "mlst_results.tsv")

#: The literal a `lineage_label` carries when stage 3 has no sequence type for
#: the sample. It is a sentinel, not a lineage: `integration` refuses on it and
#: `convergence`/`cooccurrence` refuse on it, so no result is ever grouped under
#: the string "unknown" while reading as a finding.
UNKNOWN_LINEAGE = "unknown"

#: Internal node labels generated by this pipeline's own writers.
_INTERNAL_LABEL_RE = re.compile(r"^n\d+$")

#: Characters that terminate an unquoted Newick label. Brackets are included
#: because they are structural, never part of a label.
_LABEL_TERMINATORS = "(),:;[]"


@dataclass(frozen=True)
class TreeSummary:
    """Parsed tree facts plus the validated sample correspondence."""

    path: str
    n_tips: int
    tips: Tuple[str, ...]
    manifest_ids: Tuple[str, ...]
    n_internal_nodes: int
    has_branch_lengths: bool
    newick: str

    def to_row(self) -> Dict[str, object]:
        return {
            "tree": self.path,
            "n_tips": self.n_tips,
            "n_internal_nodes": self.n_internal_nodes,
            "has_branch_lengths": self.has_branch_lengths,
            "matches_manifest": True,
        }


def extract_tips(newick: str) -> List[str]:
    """Extract tip labels from a Newick string.

    Uses a proper recursive-descent parse of the Newick grammar rather than
    character scanning, so quoted labels, nested clades and branch lengths
    are all handled correctly.

    Raises:
        DataContractError: The string is empty, unbalanced, or has no tips.
    """
    if not newick or not newick.strip():
        raise DataContractError("Tree file is empty")

    text = newick.strip().rstrip(";")
    parser = _NewickParser(text)
    tips = parser.parse()
    if not tips:
        raise DataContractError("Tree contains no tip labels")
    return tips


class _NewickParser:
    """Minimal Newick parser that collects tip labels.

    Grammar handled::

        tree      := subtree ';'
        subtree   := leaf | '(' subtree (',' subtree)* ')' [label] [length]
        leaf      := label [length]
        length    := ':' number

    Labels may be quoted with single or double quotes, in which case
    whitespace is significant and preserved.
    """

    def __init__(self, text: str) -> None:
        self.text = text
        self.pos = 0
        self.tips: List[str] = []

    # -- character helpers ----------------------------------------------
    def _peek(self) -> Optional[str]:
        return self.text[self.pos] if self.pos < len(self.text) else None

    def _skip_ws(self) -> None:
        while self.pos < len(self.text) and self.text[self.pos].isspace():
            self.pos += 1

    # -- grammar ---------------------------------------------------------
    def parse(self) -> List[str]:
        self._skip_ws()
        if self._peek() is None:
            raise DataContractError("Tree file is empty")
        self._parse_subtree()
        self._skip_ws()
        return self.tips

    def _parse_subtree(self) -> None:
        self._skip_ws()
        char = self._peek()
        if char is None:
            raise DataContractError(
                "Unexpected end of Newick string", position=self.pos
            )
        if char == "(":
            self._parse_clade()
        else:
            label = self._parse_label()
            if label and not _is_internal_label(label):
                self.tips.append(label)
        self._parse_optional_length()

    def _parse_clade(self) -> None:
        self._expect("(")
        self._parse_subtree()
        while True:
            self._skip_ws()
            char = self._peek()
            if char == ",":
                self.pos += 1
                self._parse_subtree()
            elif char == ")":
                self.pos += 1
                break
            elif char is None:
                raise DataContractError(
                    "Unbalanced Newick: missing ')'", position=self.pos
                )
            else:
                raise DataContractError(
                    "Unexpected character in Newick clade",
                    character=char,
                    position=self.pos,
                )
        # Optional internal node label, then optional branch length.
        self._skip_ws()
        if self._peek() not in (":", ",", ")", None):
            self._parse_label()
        self._parse_optional_length()

    def _parse_label(self) -> str:
        self._skip_ws()
        char = self._peek()
        if char in ("'", '"'):
            quote = char
            self.pos += 1
            start = self.pos
            while self.pos < len(self.text) and self.text[self.pos] != quote:
                self.pos += 1
            if self.pos >= len(self.text):
                raise DataContractError(
                    "Unterminated quoted label in Newick", position=start
                )
            label = self.text[start : self.pos]
            self.pos += 1  # closing quote
            return label.strip()
        start = self.pos
        # Brackets terminate a label: absorbing a stray ']' into a tip name
        # would produce a silent sample mismatch instead of a parse error.
        while self.pos < len(self.text) and self.text[self.pos] not in _LABEL_TERMINATORS:
            self.pos += 1
        return self.text[start : self.pos].strip()

    def _parse_optional_length(self) -> None:
        self._skip_ws()
        if self._peek() != ":":
            return
        self.pos += 1
        start = self.pos
        while self.pos < len(self.text) and self.text[self.pos] not in "(),;":
            self.pos += 1
        token = self.text[start : self.pos].strip()
        if token and not _looks_numeric(token):
            LOGGER.debug("Branch length %r is not numeric; retained as-is", token)

    def _expect(self, char: str) -> None:
        self._skip_ws()
        if self._peek() != char:
            raise DataContractError(
                "Expected character in Newick string",
                expected=char,
                found=self._peek(),
                position=self.pos,
            )
        self.pos += 1


def _looks_numeric(token: str) -> bool:
    try:
        float(token)
    except ValueError:
        return False
    return True


def _is_internal_label(label: str) -> bool:
    """Internal nodes in this pipeline's trees are labelled ``n<number>``."""
    return bool(_INTERNAL_LABEL_RE.match(label))


def validate_tree_samples(
    tips: Sequence[str], manifest: SampleManifest
) -> None:
    """Require the tree tip set to equal the manifest sample set exactly.

    Raises:
        TreeSampleMismatchError: With the precise set differences, on
            missing tips, extra tips, or duplicate tips.
    """
    counts: Dict[str, int] = {}
    for tip in tips:
        counts[tip] = counts.get(tip, 0) + 1
    duplicates = sorted(t for t, n in counts.items() if n > 1)
    if duplicates:
        raise TreeSampleMismatchError(
            "Tree contains duplicate tip labels",
            duplicates=",".join(duplicates[:10]),
            n_duplicates=len(duplicates),
        )

    tree_set: FrozenSet[str] = frozenset(counts)
    manifest_set: FrozenSet[str] = frozenset(manifest.sample_ids)

    missing = sorted(manifest_set - tree_set)
    extra = sorted(tree_set - manifest_set)
    if missing or extra:
        raise TreeSampleMismatchError(
            "Tree tip labels do not match the master sample manifest",
            n_missing=len(missing),
            n_extra=len(extra),
            missing_in_tree=",".join(missing[:15]),
            not_in_manifest=",".join(extra[:15]),
        )


def load_tree(path: Path) -> str:
    """Read a newick file, tolerating a trailing newline and blank lines."""
    path = Path(path)
    if not path.exists():
        raise DataContractError("Tree file not found", path=str(path))
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        raise DataContractError("Tree file is empty", path=str(path))
    return text


def summarise_tree(config: PipelineConfig, path: Path, manifest: SampleManifest) -> TreeSummary:
    """Parse and validate a tree against the manifest."""
    newick = load_tree(path)
    tips = extract_tips(newick)
    if not tips:
        raise DataContractError("Tree contains no tip labels", path=str(path))

    if config.phylogeny.require_exact_sample_match:
        validate_tree_samples(tips, manifest)
    else:
        LOGGER.warning(
            "Exact tree/manifest matching is disabled; downstream lineage "
            "analysis may be inconsistent"
        )

    internal = newick.count("(")
    has_lengths = ":" in newick
    summary = TreeSummary(
        path=str(path),
        n_tips=len(tips),
        tips=tuple(tips),
        manifest_ids=tuple(manifest.sample_ids),
        n_internal_nodes=internal,
        has_branch_lengths=has_lengths,
        newick=newick,
    )
    LOGGER.info(
        "Stage 10: tree at %s with %d tips, %d internal nodes, tips match manifest",
        path,
        summary.n_tips,
        summary.n_internal_nodes,
    )
    return summary


def load_tree_metadata(path: Path) -> Dict[str, str]:
    """Load the sample -> lineage crosswalk."""
    if not Path(path).exists():
        LOGGER.warning("Tree metadata not found: %s", path)
        return {}
    rows = read_tsv(path, required_columns=REQUIRED_TREE_METADATA)
    return {
        str(row["sample_id"]): str(row.get("lineage_label") or UNKNOWN_LINEAGE)
        for row in rows
    }


def mlst_results_path(config: PipelineConfig, mode: RunMode) -> Path:
    """Stage 3's contracted table, under this run's tool-output root."""
    return config.tool_output_root(mode).joinpath(*MLST_RESULTS_RELATIVE)


def load_lineage_labels(
    config: PipelineConfig, mode: RunMode, manifest: SampleManifest
) -> Dict[str, str]:
    """The ``sample_id -> lineage_label`` crosswalk, per `lineage.method`.

    Ruling R4: the label IS the MLST sequence type, so this reads stage 3's own
    table rather than re-deriving anything. `lineage.method` is read and
    recorded, and `LineageConfig` has already refused anything but `st`, so a
    caller cannot reach here with an unrecorded definition.

    A sample with no usable sequence type - untyped, demoted, or absent from
    the table - maps to :data:`UNKNOWN_LINEAGE` rather than being dropped: the
    manifest decides cohort membership, and a sample that silently vanishes
    from the crosswalk is a sample whose lineage is silently unstated.

    Raises:
        PipelineError: In ``REAL``, the table is absent - naming the path. In
            TEST the committed fixture is the same file, so a missing one is
            still a broken checkout rather than a broken run.
    """
    from . import mlst as mlst_stage

    method = config.lineage.method
    if method != "st":
        # Unreachable through `LineageConfig`, which validates at load time.
        # Asserted here anyway: a second definition appearing later must fail
        # at the point that would have to implement it, not produce a label
        # that claims to be a sequence type and is not.
        raise PipelineError(
            f"lineage.method is {method!r} and this stage implements only "
            f"{'st'!r}. Ruling R4: lineage_label IS the MLST sequence type from "
            "stage 3. Tree-cut lineage is deferred and must not be spelled into "
            "config until its support threshold, minimum clade size and "
            "ambiguous-tip rule have been decided.",
            method=method,
            implemented="st",
        )

    path = mlst_results_path(config, mode)
    if not path.is_file():
        raise PipelineError(
            f"No MLST results at {path}, so there are no sequence types to "
            f"build `lineage_label` from. It is written by stage 3, not by this "
            f"one: `stages/mlst.py` `_write_mlst_results` puts it at "
            f"`{'/'.join(MLST_RESULTS_RELATIVE)}` under the run's tool-output "
            f"root, which in this mode is {config.tool_output_root(mode)}. "
            f"`lineage.method` is `{method}`, and R4 says a lineage_label IS "
            "the MLST sequence type - so this is a missing stage-3 output, not "
            "an absence of lineages. Installing panaroo and gubbins does not "
            "produce it; running stage 3 does.",
            mlst_results=str(path),
            tool_output_root=str(config.tool_output_root(mode)),
            lineage_method=method,
        )

    calls = mlst_stage.load_mlst(config, path)
    labels: Dict[str, str] = {}
    untyped: List[str] = []
    for sample_id in manifest.sample_ids:
        call = calls.get(sample_id)
        sequence_type = str(call.sequence_type).strip() if call else ""
        if not sequence_type:
            labels[sample_id] = UNKNOWN_LINEAGE
            untyped.append(sample_id)
        else:
            labels[sample_id] = sequence_type
    if untyped:
        LOGGER.warning(
            "Stage 10: %d of %d samples have no MLST sequence type and are "
            "labelled %r: %s. Stage 15 refuses on that label rather than "
            "publishing a master table whose `lineage` column groups them "
            "under a sentinel.",
            len(untyped), len(manifest.sample_ids), UNKNOWN_LINEAGE,
            ",".join(untyped[:10]),
        )
    else:
        LOGGER.info(
            "Stage 10: lineage_label from %s for %d samples (method=%s)",
            path.name, len(labels), method,
        )
    return labels


def summarise_alignments(
    core_alignment: Path, snp_alignment: Path
) -> Dict[str, Optional[object]]:
    """Summarise both alignments and report the SNP density."""
    core = summarise_alignment(core_alignment)
    snp = summarise_alignment(snp_alignment)

    density: Optional[float] = None
    if snp.get("n_sites") and core.get("n_sites"):
        density = round(float(snp["n_sites"]) / float(core["n_sites"]), 6)

    return {
        "core_n_sequences": core.get("n_sequences"),
        "core_n_sites": core.get("n_sites"),
        "core_missing_fraction": core.get("missing_fraction"),
        "snp_n_sequences": snp.get("n_sequences"),
        "snp_n_sites": snp.get("n_sites"),
        "snp_density_vs_core": density,
    }


def build_tree_outputs(
    config: PipelineConfig,
    phylogeny_dir: Path,
    manifest: SampleManifest,
    *,
    mode: RunMode = RunMode.REAL,
) -> None:
    """REAL path: build `tree.nwk` and the tip crosswalk with IQ-TREE.

    Both files are inputs to :func:`run` and neither had a producer, so a REAL
    run had no tree at all. They are written under the names the stage and
    `run.py` already read rather than under IQ-TREE's own, so the seam stays the
    path.

    **The crosswalk is written with the contract's five columns.**
    `docs/data_contract.md` declares `sample_id`, `tree_tip_label`,
    `lineage_label`, `st`, `source`; this used to pass the two-column
    `REQUIRED_TREE_METADATA` to `write_tsv`, which drops the rest silently
    because `extrasaction="ignore"`. The declared schema was therefore dead
    code that hid the missing producer.

    **`lineage_label` and `st` carry the same value here, deliberately.** Under
    ruling R4 a lineage IS the MLST sequence type, so the two columns are the
    same fact recorded twice; keeping both means a later method - tree-cut, when
    it exists - becomes a visible change in the `st` column rather than a silent
    reinterpretation of a column whose name no longer says what is in it.

    **The alignment is an input here, not an output.** It comes from the
    core-alignment step, and `phylogeny.aligner` is panaroo, which has no
    installable osx-arm64 build. `:func:`require_alignment_upstream` names that
    step rather than letting a missing alignment read as an empty result.
    """
    from ..adapters import iqtree as tree_tool

    phylogeny_dir = Path(phylogeny_dir)
    settings = dict(config.raw.get("phylogeny") or {})
    alignment = phylogeny_dir / "core_snp_alignment.fasta"
    lineages = load_lineage_labels(config, mode, manifest)

    result = tree_tool.build_tree(
        alignment,
        phylogeny_dir / "iqtree",
        model=str(settings.get("models") or "GTR+G"),
        threads=int(config.runtime.get("threads", 1) or 1),
        # A fixed seed, because the search is stochastic and an unreproducible
        # tree is not a result - only a snapshot.
        seed=int(settings.get("seed", 20240617)),
        sequence_type=settings.get("sequence_type"),
        # Ruling R8: `+ASC` is only estimable once the columns that are
        # constant once gaps and N are ignored are gone, so the filter runs
        # here - before the model is used - and not inside the adapter keyed off
        # a substring of `-m`. `phylogeny.asc_drop_partially_constant` is the
        # switch, and it reaches the tool or it does not; before this it
        # parsed and was inert.
        drop_partially_constant=bool(
            settings.get("asc_drop_partially_constant", False)
        ),
    )

    phylogeny_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(result.tree, phylogeny_dir / "tree.nwk")
    rows = [
        {
            "sample_id": sample_id,
            "tree_tip_label": tip,
            "lineage_label": lineages.get(sample_id, UNKNOWN_LINEAGE),
            "st": lineages.get(sample_id, UNKNOWN_LINEAGE),
            "source": "iqtree",
        }
        for sample_id, tip in sorted(result.crosswalk.items())
    ]
    write_tsv(
        phylogeny_dir / "tree_metadata.tsv",
        rows,
        TREE_METADATA_COLUMNS,
        header_comment=_tree_provenance_header(config, settings, result, mode),
    )
    LOGGER.info(
        "Stage 10: iqtree wrote %d tips to %s, %d of them labelled by method %s",
        len(result.tip_labels), phylogeny_dir / "tree.nwk",
        sum(1 for row in rows if row["lineage_label"] != UNKNOWN_LINEAGE),
        config.lineage.method,
    )


def _tree_provenance_header(
    config: PipelineConfig,
    settings: Dict[str, object],
    result: object,
    mode: RunMode,
) -> List[str]:
    """The `#` lines above ``tree_metadata.tsv``'s header.

    Four facts belong with the crosswalk rather than in a log a reader of the
    file will never see: how `lineage_label` was defined and from which table,
    the model the search used, and how many alignment columns the
    constant-after-gaps filter removed. ``read_tsv`` skips ``#`` lines, so this
    travels with the data without changing the columns.
    """
    header = [
        f"lineage_method={config.lineage.method}",
        f"lineage_source={mlst_results_path(config, mode)}",
        f"models={settings.get('models')}",
    ]
    column_filter = getattr(result, "column_filter", None)
    if column_filter is None:
        header.append("alignment_columns_filtered=no")
    else:
        header += [
            "alignment_columns_filtered=yes",
            f"alignment_columns_in={column_filter.n_columns_in}",
            f"alignment_columns_kept={column_filter.n_columns_kept}",
            f"alignment_columns_dropped={column_filter.n_columns_dropped}",
        ]
    return header


def run(
    config: PipelineConfig,
    manifest: SampleManifest,
    mode: RunMode,
    phylogeny_dir: Path,
) -> Tuple[TreeSummary, Dict[str, object]]:
    """Stage 10 entry point."""
    phylogeny_dir = Path(phylogeny_dir)
    if mode is RunMode.REAL and not (phylogeny_dir / "tree.nwk").exists():
        build_tree_outputs(config, phylogeny_dir, manifest, mode=mode)
    summary = summarise_tree(
        config, phylogeny_dir / "tree.nwk", manifest
    )
    alignment_info: Dict[str, Optional[object]] = {}
    core = phylogeny_dir / "core_alignment.fasta"
    snp = phylogeny_dir / "core_snp_alignment.fasta"
    if core.exists() and snp.exists():
        alignment_info = summarise_alignments(core, snp)
    else:
        LOGGER.warning("Core alignments not found in %s", phylogeny_dir)
    return summary, alignment_info
